# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('label', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filesystem_label', models.CharField(max_length=64)),
                ('user_label', models.CharField(max_length=32)),
                ('manufacturer', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=64)),
                ('terabytes', models.FloatField()),
                ('install_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('value', models.IntegerField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smarty.Attribute')),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smarty.Drive')),
            ],
        ),
    ]
