# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='install_date',
            field=models.DateField(),
        ),
    ]
