# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smarty', '0002_auto_20161008_1445'),
    ]

    operations = [
        migrations.RenameField('Drive', 'filesystem_label', 'dev_disk_by_id'),
    ]
