# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarty', '0003_auto_20161008_1355'),
    ]

    operations = [
        migrations.RenameField('Drive', 'dev_disk_by_id', 'device_path'),
        migrations.AlterField('Drive', 'device_path', models.CharField(max_length = 256)),
    ]
